### ISSUE TITLE
2 windows, still image and video player

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#10]
- [ ]  http://midionodera.com/2015/strategic-growth-3-4/
- [ ]  http://midionodera.com/2015/strategic-growth-2/
- [ ]  http://midionodera.com/2015/strategic-growth/
- [ ]  http://midionodera.com/2015/humble-beginnings-3-2/
- [ ]  http://midionodera.com/2015/humble-beginnings-2/
- [ ]  http://midionodera.com/2015/humble-beginnings/
- [ ]  http://midionodera.com/2014/home-movie-10/
- [ ]  http://midionodera.com/2014/home-movie-9/
- [ ]  http://midionodera.com/2014/home-movie-8-2/
- [ ]  http://midionodera.com/2014/home-movie-7/
- [ ]  http://midionodera.com/2014/home-movie-6-8/
- [ ]  http://midionodera.com/2014/home-movie-5-2/
- [ ]  http://midionodera.com/2014/home-movie-4/
- [ ]  http://midionodera.com/2014/home-movie-03/
- [ ]  http://midionodera.com/2014/home-movie-2/
- [ ]  http://midionodera.com/2014/home-movie-1/
- [ ]  http://midionodera.com/2014/the-building-is-the-message/
- [ ]  http://midionodera.com/2014/kicking-around/
- [ ]  http://midionodera.com/2013/the-perfect-word/
- [ ]  http://midionodera.com/2013/my-junk/
- [ ]  http://midionodera.com/2013/pet-stains/
- [ ]  http://midionodera.com/2013/secrets-to-retiring-in-thailand/
- [ ]  http://midionodera.com/2013/home-sweet-home/
- [ ]  http://midionodera.com/2013/3881/
- [ ]  http://midionodera.com/2013/letting-go-3/
- [ ]  http://midionodera.com/2013/item-for-sale/
- [ ]  http://midionodera.com/2013/lost-found-3/
- [ ]  http://midionodera.com/2013/spiritual-alignment-coach/
- [ ]  http://midionodera.com/2013/you-were-drunk/
- [ ]  http://midionodera.com/2013/monkey-see-monkey-do-2/
- [ ]  http://midionodera.com/2013/classifieds-01-free-3/
- [ ]  http://midionodera.com/2012/night-garden-2/
- [ ]  http://midionodera.com/2012/night-garden/
- [ ]  http://midionodera.com/2012/between-floors/
- [ ]  http://midionodera.com/2012/the-revelation-of-vegas/
- [ ]  http://midionodera.com/2012/you-know-elephants/
- [ ]  http://midionodera.com/2012/three-poems/
- [ ]  http://midionodera.com/2012/w-53-st-between-5th-6th-ave-3/
- [ ]  http://midionodera.com/2012/ttime-flies/
- [ ]  http://midionodera.com/2012/you-decide/
- [ ]  http://midionodera.com/2012/phils-nightmare/
- [ ]  http://midionodera.com/2012/archetype/
- [ ]  http://midionodera.com/2012/rocks-2/
- [ ]  http://midionodera.com/2012/with-these-words/
- [ ]  http://midionodera.com/2011/the-art-collector/
- [ ]  http://midionodera.com/2011/ac-dc/
- [ ]  http://midionodera.com/2011/styling/
- [ ]  http://midionodera.com/2011/dogma/
- [ ]  http://midionodera.com/2011/vision/
- [ ]  http://midionodera.com/2011/reality-tv-7/
- [ ]  http://midionodera.com/2011/written-in-stone/
- [ ]  http://midionodera.com/2011/all-good-children-go-to-heaven/
- [ ]  http://midionodera.com/2011/the-best-things-are-over-before-you-know-it/
- [ ]  http://midionodera.com/2011/tackled/
- [ ]  http://midionodera.com/2011/bcn-barcelona/
- [ ]  http://midionodera.com/2011/precipitate-the-drop/
- [ ]  http://midionodera.com/2011/half-empty/
- [ ]  http://midionodera.com/2011/sunny/
- [ ]  http://midionodera.com/2011/5-reasons-i-love-the-sea/
- [ ]  http://midionodera.com/2011/inherit-the-earth/
- [ ]  http://midionodera.com/2011/on-the-beach-2/
- [ ]  http://midionodera.com/2011/stairway-to-heaven/
- [ ]  http://midionodera.com/2011/deep-thoughts/
- [ ]  http://midionodera.com/2011/but-is-it-art/
- [ ]  http://midionodera.com/2010/coast-to-coast/
- [ ]  http://midionodera.com/2010/i-have-no-memory-of-my-direction-2/

**Comment by halfempty** [comment]
@midioweb I think these are all fixed, now

**Comment by midioweb** [comment]
These videos all look good to me now. Question: When I look at them I feel some of the videos are now too small. Can I just replace the videos with a larger file? Is there a file size limit or aspect ratio limit? thanks

**Comment by halfempty** [comment]
@midioweb If videos are too small, yes, replace them with larger versions. The videos expand either to the size of the column they are in, or to their natural size.

**Comment by halfempty** [comment]
@midioweb Ps. We should start a new issue listing the ones that are too small, and then close this ticket

**Comment by halfempty** [comment]
@midioweb Pps. I've added the small to a new issue, so will close this
