### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#12]
- [x] http://midionodera.com/category/series/to-poll-or-not-to-poll/

 The link to 'Pyne' has an application error. http://getpyne.com/ 

**How about we link to an article about Pyne?
https://tech.co/pyne-tinder-social-polling-leveraging-simple-user-interface-design-competitive-market-2014-06
OR
https://techcrunch.com/2014/06/10/pyne-launch/**
---

- [x] http://midionodera.com/category/series/odd-socks/

The link 'article on DiscoveryNews' is URL https://www.rebelmouse.com/wordpress-vip-2401656056.html. This does not appear to speak about the myan calendar. Could not locate actual link for discovery news.

**How about we link to this site: 
https://www.timeanddate.com/calendar/mayan.html
OR
https://en.wikipedia.org/wiki/Maya_calendar**
---

- [x] http://midionodera.com/2012/12-x-12-x-12/

3 Broken links:

Replace 'Imaginations' with http://imaginations.csj.ualberta.ca/?p=258 

Replace '.dpi' with http://dpi.studioxx.org/en 

Replace 'Ronna bloom' with https://www.ronnabloom.com/

---

- [x] http://midionodera.com/2012/three-poems/

1 Broken link: 

Replace 'I Feel Hopeful about the Future' with https://lux.org.uk/work/i-feel-hopeful-about-the-future

---

- [x] http://midionodera.com/2009/tributaries-reflections-of-aiko-suzuki/

2 Broken links:

Unable to locate current official site for 'Ann Southam' 

**How about linking to this site:
https://www.musiccentre.ca/node/37211**

Replace 'Cindy Mochizuki' with http://www.cindymochizuki.com/

---

- [x] http://midionodera.com/2002/alphagirls/ 

1 Broken link: 

Replace 'www.interaccess.org' with http://interaccess.org/exhibition/alpha-girls

---

- [x] http://midionodera.com/2017/cfmdc-ago-present-toronto-films-from-1971-1989/

1 Broken link:

Replace 'Free tickets can be reserved here' with https://tickets.ago.net/searchEventsSummary.aro?sum=AGO+Films

**_This is past, so we don't need to link to anything_**

---

- [x] http://midionodera.com/2016/reel-asian-20th-anniversary/

1 Broken link: 

Replace 'here' with http://www.reelasian.com/festival-archives/window-horses/

---

- [x] http://midionodera.com/2013/under-new-management-video-store/

1 Broken link: 

Replace 'Klondike Institute of Art & Culture' with http://klondikeinstituteofartandculture.ca/2013/03/07/in-the-odd-gallery-under-new-management/

---

- [x] http://midionodera.com/2012/the-grand-design-museum-london/

1 Broken link: 

Cannot locate event on Museum London's site. Replace 'Museum London’s website.' with generic home http://museumlondon.ca/

---

- [x] http://midionodera.com/2011/midi-onodera-in-conversation-with-alison-loader/

2 Broken links on page: 

'Mobile Media Gallery presents Vidoodles: Intimate Cinema' http://mobilemediagallery.org/exhibitions/onodera/ 

'Mobilities.ca presents Midi Onodera: Vidoodles' http://www.mobilities.ca/2011/09/midi-onodera-vidoodles/

**We can just remove these links**
---

- [x] http://midionodera.com/2011/midi-onoderas-vidoodles-exhibition-receives-accolades/

4 Broken links: 

Replace 'Imaginations' with http://imaginations.csj.ualberta.ca/ 

Replace 'recently published a shining review' with http://imaginations.csj.ualberta.ca/?p=1141, 

Replace 'Vidoodles exhibition' with http://www.concordia.ca/cunews/main/stories/2011/09/13/art-lovers-delight-this-fall.html 

Replace 'Midi Onodera’s Vidoodles: Intimate Cinema'  with http://www.concordia.ca/cunews/main/stories/2011/09/13/art-lovers-delight-this-fall.html

---

- [x] http://midionodera.com/2011/a-movie-a-day-to-be-retweeted-at-spatial-poetics-x-powell-street-festival-society/

**We can replace the above broken link with the main festival page:
http://www.powellstreetfestival.com/**

4 Broken links. Unable to locate replacements. 

---

- [x] http://midionodera.com/2011/toronto-to-japan-hope-blossoms/

Broken link http://torontotojapan.ca unable to locate current version of website.

**We can remove this link as its an old event**
---

- [x] http://midionodera.com/2011/dpi-no-20/

Broken link, 'http://dpi.studioxx.org' http://dpi.studioxx.org/demo/?q=en/no/20/Individual-and-Collective-Liberty-in-Networks-Participants-and-Purpose-Aude-Crispel. Could not locate dpi no 20 on site. Even going to the past issues portion on the dpi website leads to a broken link. consider Replacing with generic home page http://dpi.studioxx.org/

---

- [x] http://midionodera.com/2011/imaginations/

Broken link https://www.csj.ualberta.ca/imaginations/?p=258. Replace with http://imaginations.csj.ualberta.ca/?p=258

---

- [x] http://midionodera.com/2010/imaa-on-fire-conference-june-15-19-2010-toronto/

Broken link, 'ON.Fire Independent Media Arts Conference' http://www.onfire2010.ca/. Cannot locate updated link. Consider Replacing with Facebook page https://www.facebook.com/IMAA-ONFire-independent-media-arts-conference-119933428040340/

---

- [x] http://midionodera.com/2010/archive-and-everyday-life-conference-and-exhibition/

2 Broken links 

'The Archive and Everyday Life Conference' http://www.humanities.mcmaster.ca/~english/taylor_10/Index.html cannot locate replacement link. 

**OLD event - don't need link**

'Hamilton Artists Inc' http://www.hamiltonartistsinc.on.ca/intro.shtml Replace with http://www.theinc.ca/. Consider adding http://www.theinc.ca/the-archive-and-everyday-life-exhibition/ to the page. 

---

- [x] http://midionodera.com/2010/the-8-fest-jan-29-%e2%80%93-jan-31-2010-toronto/

Broken link http://www.the8fest.com/ Replace with http://the8fest.com/

---

- [x] http://midionodera.com/2009/streaming-festival-4th-edition-20-30-november-2009/

Broken link 'mobifest.net' http://mobifest.net/home/. Cannot find current link for organization website. Consider Replacing with Facebook page https://www.facebook.com/Mobifest-121140158626/

---

- [x] http://midionodera.com/2009/nokia-mobifest-%e2%80%93-toronto-2009/

Broken link 'mobifest.net' http://mobifest.net/home/. Cannot find current link for organization website. Consider Replacing with Facebook page https://www.facebook.com/Mobifest-121140158626/

---

- [x] http://midionodera.com/2009/live-film-jack-smith-five-flaming-days-in-a-rented-world/

Broken link 'LIVE FILM! JACK SMITH! Five Flaming Days in a Rented World' http://www.arsenal-berlin.de/de/arsenal/programmtext-anzeige/article/1696/304.html?cHash=1595cf4d50 Replace with http://www.arsenal-berlin.de/en/arsenal-cinema/past-programs/single/article/1696/2804.html

---

- [x] http://midionodera.com/2009/slightseer-2001-now-playing-at-cinema-arsenal-berlin/

Broken link 'Asian Women’s Film Festival' http://www.asianwomensfilm.de/pg_home_en.html Replace with http://www.asianwomensfilm.de/

---

- [x] http://midionodera.com/2009/hamburg-international-lesbian-and-gay-film-festival-celebrates-20-years/

Broken link 'http://www.lsf-hamburg.de/das-festival/bildschoen-das-buch.html/' http://www.lsf-hamburg.de/das-festival/bildschoen-das-buch.html/ but it automatically redirrects to http://www.lsf-hamburg.de/. I cannot read the rest of the page. Consider including Amazon link https://www.amazon.de/Bildsch%C3%B6n-Lesbisch-Schwule-Filmtage-Hamburg/dp/3939542741.

---

- [x] http://midionodera.com/2009/tuff-watch-and-vote-september-11-20/

Broken link 'Toronto Urban Film Festival'  http://www.torontourbanfilmfestival.com/watch-vote.html. Perhaps replace with standard http://www.torontourbanfilmfestival.com/

---

- [x] http://midionodera.com/2009/the-basement-girl-2000-on-the-regeneration-tour/

2 Broken links 

'cinemathequeontario.ca' http://www.tiff.net/404 Replace with http://cinemathequeontario.ca/

'cfmdc.org' cannot find replacement link. CFMDC seems to have error loading page

**This link is working now**
---

- [x] http://midionodera.com/2008/mobifest-lunch-interview/

Broken link 'mobifest.net'  http://www.mobifest.net/posts/view/42, suggest to Replace with Facebook page https://www.facebook.com/Mobifest-121140158626/

---

- [x] http://midionodera.com/2008/review-passionate-ideas-behind-the-flickering-lights-of-film/

Broken link 'http://www.xtra.ca/public/National/Books_Mike_Hoolbooms_Practical_Dreamers-5568.aspx' https://www.dailyxtra.com/canada/arts-and-entertainment/books-mike-hoolbooms-practical-dreamers Replace with https://www.dailyxtra.com/books-mike-hoolbooms-practical-dreamers-37688

---

- [x] http://midionodera.com/2007/the-factory-hamilton-media-arts-centre/

Broken link 'hamiltonmediaarts.org'. http://www.hamiltonmediaarts.org./ This URL now leads to a page titled 'The Art Of Growing Cannabis'. Replace with http://factorymediacentre.ca/. According to this website contact page http://factorymediacentre.ca/contact/, the address is now 228 James Street North Hamilton, ON L8R 2L3

---

- [x] http://midionodera.com/2006/the-reel-retrospective-1997-2006/

Unresponsive link at the bottom of the page for www.reelasian.com
**Use this link:
http://www.reelasian.com/festival/festival-archive/reel-asian-program-guide-2001/**
---

- [x] http://midionodera.com/2010/purchase/

Broken link, 'CFMDC' http://www.cfmdc.org/node/3. The CFMDC site in total appears unresponsive. 'Error loading XML'

**For all these CFMDC links we can replace it with this page:
http://www.cfmdc.org/filmmaker/623
If there is a way to add a paypal system to purchase the DVDs and link it to me that would be ideal.**

**Remove the link for Art Metropole and change the sentence to:
Please contact CFMDC or Vtape for inquires or purchases.
New link for Vtape: http://www.vtape.org/artist?ai=857**
---

- [x] http://midionodera.com/2010/two/

Broken link, 'CFMDC' http://www.cfmdc.org/node/3. The CFMDC site in total appears unresponsive. 'Error loading XML'

**see note above**
---

- [x] http://midionodera.com/2010/three/

2 Broken links.

'CFMDC' http://www.cfmdc.org/node/3. The CFMDC site in total appears unresponsive. 'Error loading XML'.

**see note above**

'Domino' http://www.dominofilm.ca/. This URL not displays kitchen gadgets. Unable to locate current link that still sells 'THREE'

**Remove the link on this page for Domino**
---

- [x] http://midionodera.com/2010/i-have-no-memory-of-my-direction-2/

Broken link, 'CFMDC' http://www.cfmdc.org/node/3. The CFMDC site in total appears unresponsive. 'Error loading XML'

**replace it with this page:
http://www.cfmdc.org/filmmaker/623**
---

- [x] http://midionodera.com/distributors/

10 Broken links, 1. 'CFMDC' http://www.cfmdc.org. 2. 'The Bird That Chirped On Bathurst' 3.'The Displaced View' 4. 'Home Was Never Like This' 5. 'Idiot’s Delight' 6. 'A Performance By Jack Smith' 7. 'Ten Cents A Dance' 8. 'Three Short Films'. The CFMDC site in total appears unresponsive. 'Error loading XML'. 9. 'Moving Images Distribution' http://www.movingimages.bc.ca/ Replace with https://www.movingimages.ca/. 10. 'Ten Cents A Dance' https://www.movingimages.ca/catalogue/Experimental/Experimental_o.html#RTFToC44a . Unable to locate current link for 'Ten cents a dance" on Moving Images Distribution website

http://midionodera.com/distributors/
Under distributors remove Domino and replace with link to purchasing the DVD on my site
---

- [x] http://midionodera.com/articles/

2 Broken links 

'“CBC TV dramaHeartbreak Hoteru needs “Elvis””' http://midionodera.com/files/articles/CBCTV_Heatbreak.pdf 

'Broadside Vol 6 #9 – on super 8 films by Midi Onodera' http://midionodera.com/files/articles/BroadsideVol6#9.pdf. Unable to locate current links for articles. 

---

- [x] http://midionodera.com/2011/tuff-watch-and-vote-september-9-18/

Link to video no longer is to voting link
**Remove this link as it is no longer valid**

---

- [x] http://midionodera.com/2010/tributaries-reflections-of-aiko-suzuki-2009-at-nikkei-place-in-burnaby-bc/

Broken link 'Nikkei Place' http://www.nikkeiplace.org/upcoming-events/exhibition-opening-jun-29/  Replace with http://centre.nikkeiplace.org/past-exhibitions/. Can also consider adding http://centre.nikkeiplace.org/tributaries-reflections-of-aiko-suzuki/ to the page.

**Comment by halfempty** [comment]
@midioweb Midi, I've consolidated all the bugs that appear to have to do with broken links. These are likely fixable without much technical knowledge. Do you want to look at these on your end?

**Comment by midioweb** [comment]
Hi Marty,
Not sure if I did this correctly but just to be sure you saw my comments I put them in bold. Hope that's ok. thanks, Midi

**Comment by halfempty** [comment]
@midioweb Thank you. Do you (read: your assistants) want to fix these? Or would you like me to take care of them?

**Comment by midioweb** [comment]
Hi Marty, Brit is still out of town, but she will be back in the new year and I'll ask her to help out with these fixes. Just a reminder, I will be doing a 2018 monthly video project. thanks, Midi

**Comment by midioweb** [comment]
We can now close this link of things to do. I've gone through what my ex-student has done and made some notes where she still needs to fix things, but we will take care of it.
