### ISSUE TITLE
Incorrect series?

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#16]
the vote' http://midionodera.com/2016/the-vote/ appears in this series ("24fps") as well. Potential error as it was posted 5 years after the rest of the series?

---

- [x] http://midionodera.com/category/series/fps/

**Comment by halfempty** [comment]
@midioweb Do you know the answer to this one? Will y'all fix via WordPress?

**Comment by midioweb** [comment]
looking into it.
