### ISSUE TITLE
Video playback shows time index 0:00

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#17]
Video playback shows time index 0:00/0:00. Jumps right to the end of the video as if it was a blank video

---

- [ ] http://midionodera.com/2011/tackled/

**Comment by halfempty** [comment]
@midioweb Midi, this problem persists when I access the video directly. So I think it's a problem with the video file itself. Will y'all take this one on?

**Comment by midioweb** [comment]
Marty this is actually the only time there is no video only a jpeg with the message that there is no video this month.
