### ISSUE TITLE
White boarder around video

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#21]
White boarder around video resulting in a faint line on the right side of the frame. Playback bar appearing wider than video frame.

---

- [ ] http://midionodera.com/2009/the-corridor/

**Comment by halfempty** [comment]
@midioweb Midi, I actually don't see the problem with this one. 

- The faint white line-- I guess you could fix that in your video production process.
- The playback bar problem-- I'm just not seeing it?

**Comment by midioweb** [comment]
checked again - done
