### ISSUE TITLE
Incorrect Playback time

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#22]
- [x]  http://midionodera.com/2009/bane-of-my-existence/
- [x]  http://midionodera.com/2008/oh-oh/
- [x]  http://midionodera.com/2008/melt/
- [x]  http://midionodera.com/2008/thanks-for-the-memories/
- [x]  http://midionodera.com/2008/yesno-questions/
- [x]  http://midionodera.com/2008/dependence/
- [x]  http://midionodera.com/2008/first-day-of-my-life/
- [x]  http://midionodera.com/2008/going-down-the-road/
- [x]  http://midionodera.com/2008/candy-man/
- [x]  http://midionodera.com/2008/broken-record/
- [x]  http://midionodera.com/2008/winter-months/
- [x]  http://midionodera.com/2008/the-glamorous-life/
- [x]  http://midionodera.com/2008/big-kitty/
- [x]  http://midionodera.com/2008/hotel-lobby/
- [x]  http://midionodera.com/2008/distant-signs/
- [x]  http://midionodera.com/2008/know-it-all/
- [x]  http://midionodera.com/2008/in-out/
- [x]  http://midionodera.com/2008/the-next-station/
- [x]  http://midionodera.com/2008/look-up-in-the-sky/
- [x]  http://midionodera.com/2008/the-statement/
- [x]  http://midionodera.com/2008/down-at-your-feet/
- [x]  http://midionodera.com/2008/walk-the-dog/
- [x]  http://midionodera.com/2008/busy-mind/
- [x]  http://midionodera.com/2008/conurbation/
- [x]  http://midionodera.com/2008/beware-or-be-seen/
- [x]  http://midionodera.com/2008/dinner-time/
- [x]  http://midionodera.com/2008/getting-it-right/
- [x]  http://midionodera.com/2008/daily-routine/
- [x]  http://midionodera.com/2008/carnival/
- [x]  http://midionodera.com/2008/anthropomorphism-334/
- [x]  http://midionodera.com/2008/not-all-fun-games/
- [x]  http://midionodera.com/2008/citrus-city/
- [x]  http://midionodera.com/2008/honey/
- [x]  http://midionodera.com/2008/parking-karma/
- [x]  http://midionodera.com/2008/its-not-the-heat/
- [x]  http://midionodera.com/2008/andare-allestro/
- [x]  http://midionodera.com/2008/grazie-gesu/
- [x]  http://midionodera.com/2008/trip-of-a-lifetime/
- [x]  http://midionodera.com/2008/taking-precautions/
- [x]  http://midionodera.com/2008/lavoro/
- [x]  http://midionodera.com/2008/allegory-of-the-magic-kingdom/
- [x]  http://midionodera.com/2008/juliet-is-in/
- [x]  http://midionodera.com/2008/wings-of-the-angels-2/
- [x]  http://midionodera.com/2008/taking-care/
- [x]  http://midionodera.com/2008/nectar-of-gods/
- [x]  http://midionodera.com/2008/just-down-the-block/
- [x]  http://midionodera.com/2008/greenthumb/
- [x]  http://midionodera.com/2008/the-bad-seed/
- [x]  http://midionodera.com/2008/shock-n-awe/
- [x]  http://midionodera.com/2008/cooking-101/
- [x]  http://midionodera.com/2008/bird-flew/
- [x]  http://midionodera.com/2008/cant-we-all-just-get-along/
- [x]  http://midionodera.com/2008/speechless/
- [x]  http://midionodera.com/2008/mouton-v1/
- [x]  http://midionodera.com/2008/learning-can-be-fun/
- [x]  http://midionodera.com/2008/going-home/
- [x]  http://midionodera.com/2008/a-little-off-the-top/

**Comment by halfempty** [comment]
@midioweb Midi, I checked the first six of these and I don't see the issue. Do you? The playback time appears accurate... should I keep checking the others?

**Comment by midioweb** [comment]
If you look at the playback bar, you will see 5:44 as the end time for the first video, but this is incorrect. Not sure how it jumped to be 5:44 when the video itself is very short. This is the problem. The second video says 5:43 which is also incorrrect. I believe its the same problem with all these videos.

**Comment by midioweb** [comment]
Videos of A Movie A Day(2008) will be deleted all and replaced into good versions with the right order.
