### ISSUE TITLE
Movie a Day, 3 videos with the same date

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#23]
Under Movie a Day, there are 3 videos with the same Jan. 1 date. I am not sure what happened here but I'd like to revisit these titles and make sure they are correct

---

- [ ] http://midionodera.com/category/series/a-movie-a-day/

**Comment by halfempty** [comment]
@midioweb Midi, are these supposed to have this date? If no, can y'all change them via WordPress?

**Comment by midioweb** [comment]
I am closing this issue. We are re-ordering and uploading all the Movie a day videos.
