### ISSUE TITLE
No video specified

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#24]
like the other films in the portfolio section 
(http://midionodera.com/2005/i-have-no-memory-of-my-direction/)

http://midionodera.com/1979/reality-illusion/
http://midionodera.com/1979/contemplation/
http://midionodera.com/1980/filter-queen/
http://midionodera.com/1981/food-trilogy/
http://midionodera.com/1981/home-movies/
http://midionodera.com/1981/the-bird-that-chirped-on-bathurst/
http://midionodera.com/1982/endocrine/
http://midionodera.com/1983/home-was-never-like-this/
http://midionodera.com/1983/idots-delight/
http://midionodera.com/1984/ville-quelle-ville/
http://midionodera.com/1985/made-in-japan/
http://midionodera.com/1985/the-dead-zone/ 
http://midionodera.com/1985/ten-cents-a-dance-parallax/
http://midionodera.com/1988/thennow/
http://midionodera.com/1988/the-displaced-view/
http://midionodera.com/1989/general-idea-artist-profile/
http://midionodera.com/1990/heartbreak-hoteru/
http://midionodera.com/1990/david-cronenberg-artists-profile/
http://midionodera.com/1992/a-performance-by-jack-smith/
http://midionodera.com/1995/skin-deep/
http://midionodera.com/2000/the-basement-girl/
http://midionodera.com/2001/slightseer/
http://midionodera.com/2002/nobody-knows/
http://midionodera.com/2012/the-grand-design-2012-2/

**Comment by halfempty** [comment]
@midioweb The issue with these is that there's no video specified at all. Can we get clips in the modern format?

**Comment by midioweb** [comment]
everything is checked and done
