### ISSUE TITLE
Static image shows an overlap

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#27]
Static image before play is pressed shows an overlap with with bottom of the frame and the playback bar

---

- [x] http://midionodera.com/2008/happy-new-year/
- [x] http://midionodera.com/2008/nature-calls/
- [x] http://midionodera.com/2008/navel-gazing/
- [x] http://midionodera.com/2008/middle-of-the-desert/
- [x] http://midionodera.com/2008/ticket-to-ride/
- [x] http://midionodera.com/2008/the-problem-is-space-is-transparent/
- [x] http://midionodera.com/2008/doorknob-shopping/
- [x] http://midionodera.com/2008/birds-of-paradise/
- [x] http://midionodera.com/2008/tiny-house/
- [x] http://midionodera.com/2008/bingo/
- [x] http://midionodera.com/2005/i-have-no-memory-of-my-direction/

**Comment by halfempty** [comment]
@midioweb Either this one is fixed... or I misunderstand the issue. Please let me know if you're still seeing the problem.

**Comment by midioweb** [comment]
Marty, I think I need to look at replacing the "I have no memory" clip as it seems a bit pixelated and the the Tiny House link looks like it has too much black on it at the end. Will look into this.

**Comment by midioweb** [comment]
Videos of the series A Movie A Day(2008) will be changed into the right order and good version later.
