### ISSUE TITLE
Quicktime Videos

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#28]
Video player unresponsive in Firefox. Chrome automatically prompts a file download

---

- [ ] http://midionodera.com/2008/call-to-prayer/
- [x] http://midionodera.com/2010/tributaries-reflections-of-aiko-suzuki-2009-at-nikkei-place-in-burnaby-bc/
- [ ] http://midionodera.com/2008/wondrous-light/

**Comment by halfempty** [comment]
@midioweb This is a QuickTime video. I believe QuickTime is no longer supported by Chrome at all. Can your team replace this with the current format?

**Comment by midioweb** [comment]
ok we'll look into this

**Comment by midioweb** [comment]
I am closing this issue. We are re-ordering and uploading all the Movie a day videos.
