### ISSUE TITLE
Add "watch preview"

### ISSUE THREAD

**Issue by midioweb** [halfempty/onodera#29]
like the other films in the portfolio section 
(http://midionodera.com/2005/i-have-no-memory-of-my-direction/)

http://midionodera.com/1979/reality-illusion/
http://midionodera.com/1979/contemplation/
http://midionodera.com/1980/filter-queen/
http://midionodera.com/1981/food-trilogy/
http://midionodera.com/1981/home-movies/
http://midionodera.com/1981/the-bird-that-chirped-on-bathurst/
http://midionodera.com/1982/endocrine/
http://midionodera.com/1983/home-was-never-like-this/
http://midionodera.com/1983/idots-delight/
http://midionodera.com/1984/ville-quelle-ville/
http://midionodera.com/1985/made-in-japan/
http://midionodera.com/1985/the-dead-zone/ 
http://midionodera.com/1985/ten-cents-a-dance-parallax/
http://midionodera.com/1988/thennow/
http://midionodera.com/1988/the-displaced-view/
http://midionodera.com/1989/general-idea-artist-profile/
http://midionodera.com/1990/heartbreak-hoteru/
http://midionodera.com/1990/david-cronenberg-artists-profile/
http://midionodera.com/1992/a-performance-by-jack-smith/
http://midionodera.com/1995/skin-deep/
http://midionodera.com/2000/the-basement-girl/
http://midionodera.com/2001/slightseer/
http://midionodera.com/2002/nobody-knows/
http://midionodera.com/2012/the-grand-design-2012-2/

**Comment by halfempty** [comment]
@midioweb This is something y'all can change on your end. On the Edit screen there's a checkbox for Movie Type: Trailer...

![image](https://user-images.githubusercontent.com/775543/34390998-d126fcd8-eb08-11e7-8e70-d42591e7f85c.png)

**Comment by midioweb** [comment]
ok thanks, I'm compiling a list of items to do and trying to arrange an alternative assistant to help out. I'll add this on my end.

**Comment by midioweb** [comment]
http://midionodera.com/2005/i-have-no-memory-of-my-direction/ - can you please change the template to remove "alternative format .MOV" option. When this is done we can close this item. thanks!

**Comment by midioweb** [comment]
DONE
