### ISSUE TITLE
Small videos

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#30]
These are all somewhat small. Should they be replaced with new, larger files? Some are smaller than others.

---

- [x] http://midionodera.com/2015/strategic-growth-3-4/
- [x] http://midionodera.com/2015/strategic-growth-2/
- [x] http://midionodera.com/2015/strategic-growth/
- [x] http://midionodera.com/2015/humble-beginnings-3-2/
- [x] http://midionodera.com/2015/humble-beginnings-2/
- [x] http://midionodera.com/2015/humble-beginnings/
- [x] http://midionodera.com/2013/the-perfect-word/
- [x] http://midionodera.com/2013/my-junk/
- [x] http://midionodera.com/2013/pet-stains/
- [x] http://midionodera.com/2013/secrets-to-retiring-in-thailand/
- [x] http://midionodera.com/2013/home-sweet-home/
- [x] http://midionodera.com/2013/3881/
- [x] http://midionodera.com/2013/letting-go-3/
- [x] http://midionodera.com/2013/item-for-sale/
- [x] http://midionodera.com/2013/you-were-drunk/
- [x] http://midionodera.com/2013/monkey-see-monkey-do-2/
- [ ] http://midionodera.com/2012/night-garden-2/
- [ ] http://midionodera.com/2012/night-garden/
- [x] http://midionodera.com/2012/between-floors/
- [x] http://midionodera.com/2012/the-revelation-of-vegas/
- [x] http://midionodera.com/2012/you-know-elephants/
- [x] http://midionodera.com/2012/three-poems/
- [x] http://midionodera.com/2012/w-53-st-between-5th-6th-ave-3/
- [x] http://midionodera.com/2012/ttime-flies/
- [x] http://midionodera.com/2012/you-decide/
- [x] http://midionodera.com/2012/phils-nightmare/
- [x] http://midionodera.com/2012/archetype/
- [ ] http://midionodera.com/2012/rocks-2/
- [ ] http://midionodera.com/2012/with-these-words/
- [x] http://midionodera.com/2011/the-art-collector/
- [x] http://midionodera.com/2011/styling/
- [ ] http://midionodera.com/2011/dogma/
- [x] http://midionodera.com/2011/reality-tv-7/
- [x] http://midionodera.com/2011/all-good-children-go-to-heaven/
- [x] http://midionodera.com/2011/the-best-things-are-over-before-you-know-it/
- [x] http://midionodera.com/2011/tackled/
- [x] http://midionodera.com/2011/precipitate-the-drop/
- [x] http://midionodera.com/2011/sunny/
- [x] http://midionodera.com/2011/5-reasons-i-love-the-sea/
- [ ] http://midionodera.com/2011/on-the-beach-2/
- [ ] http://midionodera.com/2011/deep-thoughts/
- [x] http://midionodera.com/2010/coast-to-coast/
- [x] http://midionodera.com/2010/i-have-no-memory-of-my-direction-2/
- [x] http://midionodera.com/2012/grief-without-fantasy/
- [x] http://midionodera.com/2012/on-holiday/
- [ ] http://midionodera.com/2012/use-these-poems-2012/
- [x] http://midionodera.com/2010/aleatoria-2/
- [x] http://midionodera.com/2010/aleatoria/
- [x] http://midionodera.com/2010/we-stand-on-guard/
- [ ] http://midionodera.com/2010/desperate-measures/
- [x] http://midionodera.com/2010/california-dreaming/
- [x] http://midionodera.com/2010/the-fitting-room/
- [x] http://midionodera.com/2010/marooned/
- [ ] http://midionodera.com/2010/recurring-nightmare/
- [x] http://midionodera.com/2010/cross-dissolve-into-middle-age/
- [x] http://midionodera.com/2010/the-hotel-elevator/
- [x] http://midionodera.com/2010/america-any-way-you-slice-it/
- [x] http://midionodera.com/2010/moon-over-miami/
- [x] http://midionodera.com/2010/mmx/
- [x] http://midionodera.com/2010/the-game-that-people-play/
- [x] http://midionodera.com/2010/not-many-mushrooms-at-portobello-market/
- [x] http://midionodera.com/2009/move-2009-short-version/
- [x] http://midionodera.com/2009/move-2009-long-version/

**Comment by midioweb** [comment]
links unchecked are missing files or need to be replaced later
