### ISSUE TITLE
under Portfolio make new heading 2015 -

### ISSUE THREAD

**Issue by midioweb** [halfempty/onodera#31]
Hi Marty, Can you please create a new tab for the most recent titles? It should be 2015 - 2018. In this section, can you add the information for Annual Report 2015, To Poll or Not to Poll (2016), Lonely Videos (2017) and a template for adding a new title for 2017. thanks!

**Comment by halfempty** [comment]
@midioweb Okay, I've added this... 
http://midionodera.com/category/films/2015-2018/
