### ISSUE TITLE
Alphagirls link

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#5]
The last time I looked the link for alphagirls.ca was broken. It should point to the alphagirls website.

See the second entry for the broken link http://midionodera.com/?s=alphagirls

**Comment by halfempty** [comment]
@midioweb Okay, I think this is fixed. Midi, can you confirm?

**Comment by midioweb** [comment]
Hi Marty
This looks good now.
thanks…and thanks for the call this afternoon, very helpful.

Midi
