### ISSUE TITLE
Video playback only has audio from the left side

### ISSUE THREAD

**Issue by halfempty** [halfempty/onodera#8]
On learning colors: Video playback only has audio from the left side

---

- [ ] http://midionodera.com/2017/learning-colors/

**Comment by halfempty** [comment]
@midioweb Midi, I think this one has to do with the video file itself. Will y'all take this on?

**Comment by midioweb** [comment]
ok am looking at this

**Comment by midioweb** [comment]
it is replaced by the good version.
